### ISSUE TITLE
ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"

### ISSUE THREAD

**Issue by StarDustEins** [pumpkin4gb/bzz#2]
#1 ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"     what does it mean?     i run it in my terminal but returns plural ip addresses

**Comment by pumpkin4gb** [comment]
You may have multiple network adapters, I guess? This part of the code is only used to distinguish the server, so please feel free to modify the variable **ip** to whatever you like.
