### ISSUE TITLE
step2.sh: 11: Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by hopepanwei** [pumpkin4gb/bzz#3]
step2.sh启动报错 位置：``` for ((i=1; i<=tCnt; i ++))```

另一个问题：step1.sh运行后关闭再次运行还是执行的上次执行的节点

**Comment by pumpkin4gb** [comment]
你好，我测试了一下没有发现这两个问题。
看情况似乎是找不到记录节点次数的.showcnt.txt文件，或该文件没有被创建，也许可以检查一下脚本位置与脚本权限？
为了多服务器部署时省事，我一开始写时是按root来部署的。如果是其他用户修改一下脚本文件中相应位置即可。

**Comment by hopepanwei** [comment]
找到原因了，bash被替换成dash，导致showcnt文件未能成功记录，继而导致后续问题，还原成bash后正常了
详见：https://blog.csdn.net/u014470581/article/details/51493150

**Comment by pumpkin4gb** [comment]
OK，多谢反馈哈
